// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: feed_follow.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const followFeed = `-- name: FollowFeed :exec
INSERT INTO feed_follow (id, user_id, feed_id)
VALUES ($1, $2, $3)
`

type FollowFeedParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
	FeedID uuid.UUID
}

func (q *Queries) FollowFeed(ctx context.Context, arg FollowFeedParams) error {
	_, err := q.db.ExecContext(ctx, followFeed, arg.ID, arg.UserID, arg.FeedID)
	return err
}
